workflows:
  android-apk:
    name: APK Final
    environment:
      flutter: 3.16.9
    scripts:
      - flutter pub get
      - flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
