workflows:
  android-apk:
    name: Nutri Control APK
    environment:
      flutter: 3.16.9
    scripts:
      - flutter clean
      - flutter pub get
      # REMOVEMOS O --no-overwrite PARA GERAR ESTRUTURA NOVA E COMPLETA
      - flutter create --platforms=android .
      # COPIAMOS DE VOLTA O NOSSO ARQUIVO COM PERMISSÃO E DADOS
      - cp -f android/app/src/main/AndroidManifest.xml android/app/src/main/AndroidManifest.xml
      - echo "minSdkVersion=20" >> android/app/gradle.properties
      - echo "compileSdkVersion=34" >> android/app/gradle.properties
      - cp -f google-services.json android/app/
      - flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
