name: controle_validade
description: Aplicativo de Controle de Estoque e Validade
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  intl: ^0.19.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
