name: controle_validade
description: Controle de estoque e validade com leitor de código
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  mobile_scanner: ^5.0.0

flutter:
  uses-material-design: true
